version: '3.4'

services:
  todofinal:
    image: todofinal
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8002:8002
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
